export function handleError(error) {
    alert(`An error has occured: ` + error.message)
}